name: nlp_grp1

channels:
 - defaults
 - conda-forge

dependencies:
 - python
 - pyspark
 - scikit-learn
 - numpy
 - pandas
 - jupyter
 - notebook
 - regex
 - nltk
 - dill
 - snorkel
 - spacy
 - pytorch
 - transformers
 - matplotlib
 - pip
 - pip:
   - spark-nlp