name: NLP_grp1

channels:
 - defaults
 - conda-forge

dependencies:
 - python=3.13.2
 - scikit-learn
 - numpy=2.2.4
 - pandas=2.2.3
 - jupyter
 - notebook
 - regex
 - nltk
 - dill=0.3.8
 - pytorch
 - transformers